<?php
/**
 * @file
 * Code for the Integration module.
 */

include_once 'integration.inc';

/**
 * Implements hook_views_pre_view().
 * 
 * Add "Add content" links to integration views.
 */
function integration_views_pre_view($view, $display_id, $args) {
  //Find all  integrations.
  $integrations = module_invoke_all('integration');
  foreach ($integrations as $integration) { 
    if (!empty($integration['views'][$view->name][$display_id]['add_content_link'])) {
      if (empty($integration['entity']['node'])) {
        continue;
      }
      foreach($integration['entity']['node'] as $bundle => $options) {
        if (!empty($options['add_content_link'])) {
          $bundles[$bundle] = $bundle;
        }
        $areas = $integration['views'][$view->name][$display_id]['add_content_link']['areas'];
        integration_views_content_link($view, $display_id, $bundles, $areas);
      }
    }
  }
}
